[package]
name = "beamng-terrain-generator"
version = "1.0.0"
description = "Generate BeamNG.drive maps from real-world data"
authors = ["Ivan Cherepok"]
license = "Apache-2.0"
repository = "https://github.com/yourusername/beamng-terrain-generator"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open", "dialog-all", "fs-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
image = "0.24"
osmio = "0.1"
geo = "0.27"
geo-types = "0.7"
zip = "0.6"
walkdir = "2.4"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true