[package]
name = "bnggen"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = "0.6"
anyhow = "1.0"
quick-xml = "0.25"
geo = "0.24"
geojson = "0.23"
